---
name: autoupdate
on:
  schedule:
    - cron: '*/10 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  autoupdate:
    runs-on: ubuntu-20.04
    name: Auto-update

    steps:
      - id: branch
        name: Generate feature branch name
        run: echo "::set-output name=ref::chore/autoupdate-$(date +%h-%d)"

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create feature branch
        run: git switch -c ${{ steps.branch.outputs.ref }}

      - name: Update something
        run: echo "hello world" >> testfile.txt

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # Optional, but recommended
          # Defaults to "Apply automatic changes"
          commit_message: 'chore: auto-update'
          push_options: -u origin HEAD

          # Optional commit user and author settings
          commit_user_name: GitHub Actions
          commit_user_email: actions@github.com
          commit_author: GitHub Actions <actions@github.com>

      - name: Create pull request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: '${{ steps.branch.outputs.ref }}'
          destination_branch: 'master'
          pr_title: 'chore: auto-update testfile'
          pr_reviewer: 'robertrossmann'
          pr_label: 'autoupdate'
          pr_allow_empty: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
