---
name: autoupdate
on:
  schedule:
    - cron: '*/10 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  autoupdate:
    runs-on: ubuntu-20.04
    name: Auto-update

    steps:
      - id: branch
        name: Generate feature branch name
        run: echo "::set-output name=ref::chore/autoupdate-$(date +%h-%d)"

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create feature branch
        run: git switch -c ${{ steps.branch.outputs.ref }}

      - name: Update something
        run: echo "hello world" >> testfile.txt

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # Optional, but recommended
          # Defaults to "Apply automatic changes"
          commit_message: 'chore: auto-update'

          # Optional branch name where commit should be pushed to.
          # Defaults to the current branch.
          branch: ${{ steps.branch.outputs.ref }}

          # Optional commit user and author settings
          # commit_user_name: My GitHub Actions Bot # defaults to "GitHub Actions"
          # commit_user_email: my-github-actions-bot@example.org # defaults to "actions@github.com"
          # commit_author: Author <actions@github.com> # defaults to author of the commit that triggered the run

      - name: Create pull request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: '${{ steps.branch.outputs.ref }}'
          destination_branch: 'master'
          pr_title: 'chore: auto-update testfile'
          pr_reviewer: 'robertrossmann'
          pr_label: 'autoupdate'
          pr_allow_empty: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
